# Generated by Django 5.1.1 on 2025-09-24 19:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=80)),
                ('rooms', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeaturesDaily',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('dt', models.DateField()),
                ('is_holiday', models.BooleanField(default=False)),
                ('event_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'dt'], name='listings_fe_city_d31fdd_idx')],
                'unique_together': {('city', 'dt')},
            },
        ),
        migrations.CreateModel(
            name='MarketSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=80)),
                ('dt', models.DateField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('occupancy', models.DecimalField(decimal_places=2, max_digits=5)),
                ('n_listings', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['city', 'dt'], name='listings_ma_city_6d7772_idx')],
                'unique_together': {('city', 'dt')},
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('min_nights', models.PositiveIntegerField(default=1)),
                ('blocked', models.BooleanField(default=False)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar', to='listings.listing')),
            ],
            options={
                'indexes': [models.Index(fields=['listing', 'dt'], name='listings_ca_listing_4e54a8_idx')],
                'unique_together': {('listing', 'dt')},
            },
        ),
        migrations.CreateModel(
            name='Override',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField()),
                ('manual_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='listings.listing')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['listing', 'dt'], name='listings_ov_listing_c02d17_idx')],
                'unique_together': {('listing', 'dt')},
            },
        ),
    ]
