# Generated by Django 5.1.1 on 2025-09-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_id', models.UUIDField()),
                ('dt', models.DateField()),
                ('rec_price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('conf_low', models.DecimalField(decimal_places=2, max_digits=8)),
                ('conf_high', models.DecimalField(decimal_places=2, max_digits=8)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['listing_id', 'dt'], name='recommendat_listing_246421_idx')],
                'unique_together': {('listing_id', 'dt')},
            },
        ),
    ]


# To see the data

# docker compose exec db psql \
#   -U ${POSTGRES_USER:-postgres} \
#   -d ${POSTGRES_DB:-pricing} \
#   -c "select listing_id, dt, rec_price, conf_low, conf_high, reason
#       from recommendations_recommendation
#       order by dt desc
#       limit 10;"
